icons = "awesome"

[theme]
name = "native"

[[block]]
block = "time"
[block.format]
full = "%I:%M %p"

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{signal_strength}"

[[block]]
block = "cpu"
format = " {frequency}({utilization})"

[[block]]
block = "memory"
format_mem = "{mem_used;M}/{mem_total}({mem_total_used_percents})"
clickable = false

[[block]]
block = "backlight"

[[block]]
block = "battery"
format = " {percentage}"
