[icons]
icons = "material-nf"

[[block]]
block = "time"
interval = 5
format = " $icon  $timestamp.datetime(f:'%a %d/%I:%M %p') "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon  $signal_strength "

[[block]]
block = "cpu"

[[block]]
block = "backlight"

[[block]]
block = "bluetooth"
mac = "1C:52:16:97:D1:ED"

[[block]]
block = "battery"
format = " $icon $percentage "
