[theme]
name = "native"

[[block]]
block = "time"
[block.format]
full = "%I:%M %p"

[[block]]
block = "cpu"

[[block]]
block = "memory"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
